# Generated by Django 2.2 on 2019-05-31 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20190531_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(max_length=1000, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True)),
                ('ingredients', models.CharField(max_length=5000, null=True)),
                ('shops', models.CharField(max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000, null=True, unique=True)),
                ('picture', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookmarkProduct',
        ),
    ]
