# Generated by Django 2.2 on 2019-06-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190531_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
