language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

branches:
  only:
    - staging
