# Generated by Django 2.2 on 2019-05-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
