# Generated by Django 2.2 on 2019-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20190516_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ingredients',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='ingredients',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
