# Generated by Django 2.2 on 2019-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20190517_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ingredients',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='ingredients',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
