# Generated by Django 2.2 on 2019-05-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_auto_20190520_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='link',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
