# Generated by Django 2.2 on 2019-05-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_auto_20190520_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
