# Generated by Django 2.2 on 2019-05-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0008_auto_20190522_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
