# Generated by Django 2.2 on 2019-05-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0009_auto_20190522_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
