# Generated by Django 2.2.1 on 2019-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0011_product_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
